//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplierInfo
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public long SupplierId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public System.DateTime PeriodTo { get; set; }
    
        public virtual Product Products { get; set; }
        public virtual Supplier Suppliers { get; set; }
    }
}
